name: sofiakb_fireblaze_flutter
description: The packages allows to easily manage firebase requests.
maintainer: Sofiane Akbly
version: 1.0.0-beta.20

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  intl: ^0.18.1
  localstorage: ^4.0.1+4
  mime: ^1.0.4

scripts:
  release: ./scripts/release.sh