name: sofiakb_fireblaze_flutter
description: The packages allows to easily manage firebase requests.
maintainer: Sofiane Akbly
version: 1.0.0-beta.26

environment:
  sdk: ">3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  intl: ^0.19.0
  localstorage: ^4.0.1+4
  mime: ^1.0.4

scripts:
  release: ./scripts/release.sh