name: sofiakb_fireblaze_flutter
description: The packages allows to easily manage firebase requests.
maintainer: Sofiane Akbly
version: 2.1.0

environment:
  sdk: ">3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase / google dependencies
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7

  # other dependencies
  collection: ^1.18.0
  intl: ^0.20.1
  localstorage: ^4.0.1+4
  mime: ^2.0.0
  universal_io: ^2.2.2

scripts:
  release: ./scripts/release.sh
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  firebase_storage_mocks: ^0.7.0
