name: sofiakb_fireblaze_flutter
description: The packages allows to easily manage firebase requests.
maintainer: Sofiane Akbly
version: 2.0.0-dev.1

environment:
  sdk: ">3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  intl: ^0.19.0
  localstorage: ^4.0.1+4
  mime: ^1.0.4
  collection: ^1.18.0

scripts:
  release: ./scripts/release.sh
dev_dependencies:
  flutter_lints: ^3.0.1
